// Pre-built example sentences for hanzi characters
// Format: { "char": [{"zh":"...","pinyin":"...","ko":"..."},{"zh":"...","pinyin":"...","ko":"..."}] }
var EXAMPLE_DATA = {
"一":[{"zh":"我买了一本书。","pinyin":"Wǒ mǎi le yī běn shū.","ko":"나는 책 한 권을 샀다."},{"zh":"一起去吃饭吧。","pinyin":"Yīqǐ qù chīfàn ba.","ko":"같이 밥 먹으러 가자."}],
"二":[{"zh":"我有二十块钱。","pinyin":"Wǒ yǒu èrshí kuài qián.","ko":"나는 20위안이 있다."},{"zh":"二月是最短的月份。","pinyin":"Èr yuè shì zuì duǎn de yuèfèn.","ko":"2월은 가장 짧은 달이다."}],
"三":[{"zh":"我买了三枚邮票。","pinyin":"Wǒ mǎi le sān méi yóupiào.","ko":"나는 우표 세 장을 샀다."},{"zh":"三个人一起走。","pinyin":"Sān gè rén yīqǐ zǒu.","ko":"세 사람이 함께 걸었다."}],
"四":[{"zh":"教室里有四张桌子。","pinyin":"Jiàoshì lǐ yǒu sì zhāng zhuōzi.","ko":"교실에 책상이 네 개 있다."},{"zh":"四季分明。","pinyin":"Sìjì fēnmíng.","ko":"사계절이 뚜렷하다."}],
"五":[{"zh":"我每天工作五个小时。","pinyin":"Wǒ měitiān gōngzuò wǔ gè xiǎoshí.","ko":"나는 매일 5시간 일한다."},{"zh":"五颜六色的花朵。","pinyin":"Wǔyánliùsè de huāduǒ.","ko":"알록달록한 꽃들."}],
"六":[{"zh":"他六岁开始学钢琴。","pinyin":"Tā liù suì kāishǐ xué gāngqín.","ko":"그는 6살에 피아노를 배우기 시작했다."},{"zh":"今天是六月一号。","pinyin":"Jīntiān shì liù yuè yī hào.","ko":"오늘은 6월 1일이다."}],
"七":[{"zh":"一周有七天。","pinyin":"Yī zhōu yǒu qī tiān.","ko":"일주일은 7일이다."},{"zh":"七点钟上课。","pinyin":"Qī diǎn zhōng shàngkè.","ko":"7시에 수업이 시작된다."}],
"八":[{"zh":"八月是夏天。","pinyin":"Bā yuè shì xiàtiān.","ko":"8월은 여름이다."},{"zh":"我家有八口人。","pinyin":"Wǒ jiā yǒu bā kǒu rén.","ko":"우리 집은 여덟 식구이다."}],
"九":[{"zh":"九点钟开会。","pinyin":"Jiǔ diǎn zhōng kāihuì.","ko":"9시에 회의가 시작된다."},{"zh":"九月开学。","pinyin":"Jiǔ yuè kāixué.","ko":"9월에 개학한다."}],
"十":[{"zh":"我等了十分钟。","pinyin":"Wǒ děng le shí fēnzhōng.","ko":"나는 10분을 기다렸다."},{"zh":"十全十美。","pinyin":"Shíquánshíměi.","ko":"십전십미, 완벽하다."}],
"百":[{"zh":"这本书一百块。","pinyin":"Zhè běn shū yībǎi kuài.","ko":"이 책은 100위안이다."},{"zh":"百花齐放。","pinyin":"Bǎihuā qífàng.","ko":"백 가지 꽃이 한꺼번에 피다."}],
"千":[{"zh":"千里之行始于足下。","pinyin":"Qiānlǐ zhī xíng shǐ yú zú xià.","ko":"천리 길도 한 걸음부터 시작된다."},{"zh":"这台电脑三千块。","pinyin":"Zhè tái diànnǎo sānqiān kuài.","ko":"이 컴퓨터는 3000위안이다."}],
"萬":[{"zh":"万事如意。","pinyin":"Wànshì rúyì.","ko":"만사여의, 모든 일이 뜻대로 되길."},{"zh":"长城万里长。","pinyin":"Chángchéng wànlǐ cháng.","ko":"만리장성은 만리나 길다."}],
"人":[{"zh":"中国人很友好。","pinyin":"Zhōngguó rén hěn yǒuhǎo.","ko":"중국 사람들은 친절하다."},{"zh":"这个人是我的朋友。","pinyin":"Zhège rén shì wǒ de péngyou.","ko":"이 사람은 내 친구이다."}],
"大":[{"zh":"这个房间很大。","pinyin":"Zhège fángjiān hěn dà.","ko":"이 방은 매우 크다."},{"zh":"他是大学生。","pinyin":"Tā shì dàxuéshēng.","ko":"그는 대학생이다."}],
"小":[{"zh":"我有一只小猫。","pinyin":"Wǒ yǒu yī zhī xiǎo māo.","ko":"나는 작은 고양이 한 마리가 있다."},{"zh":"小心路滑。","pinyin":"Xiǎoxīn lù huá.","ko":"길이 미끄러우니 조심하세요."}],
"中":[{"zh":"我在学中文。","pinyin":"Wǒ zài xué zhōngwén.","ko":"나는 중국어를 배우고 있다."},{"zh":"中国是一个大国。","pinyin":"Zhōngguó shì yīgè dàguó.","ko":"중국은 큰 나라이다."}],
"日":[{"zh":"今日天气很好。","pinyin":"Jīnrì tiānqì hěn hǎo.","ko":"오늘 날씨가 좋다."},{"zh":"日出很美。","pinyin":"Rìchū hěn měi.","ko":"일출이 아름답다."}],
"月":[{"zh":"月亮很圆。","pinyin":"Yuèliang hěn yuán.","ko":"달이 둥글다."},{"zh":"这个月很忙。","pinyin":"Zhège yuè hěn máng.","ko":"이번 달은 바쁘다."}],
"水":[{"zh":"请给我一杯水。","pinyin":"Qǐng gěi wǒ yī bēi shuǐ.","ko":"물 한 잔 주세요."},{"zh":"水很清澈。","pinyin":"Shuǐ hěn qīngchè.","ko":"물이 매우 맑다."}],
"火":[{"zh":"小心火烛。","pinyin":"Xiǎoxīn huǒzhú.","ko":"불조심하세요."},{"zh":"火车站在哪里？","pinyin":"Huǒchē zhàn zài nǎlǐ?","ko":"기차역이 어디에 있나요?"}],
"山":[{"zh":"那座山很高。","pinyin":"Nà zuò shān hěn gāo.","ko":"저 산은 매우 높다."},{"zh":"我喜欢爬山。","pinyin":"Wǒ xǐhuan páshān.","ko":"나는 등산을 좋아한다."}],
"木":[{"zh":"这张桌子是木头做的。","pinyin":"Zhè zhāng zhuōzi shì mùtou zuò de.","ko":"이 책상은 나무로 만들었다."},{"zh":"树木很茂盛。","pinyin":"Shùmù hěn màoshèng.","ko":"나무가 무성하다."}],
"天":[{"zh":"今天是星期一。","pinyin":"Jīntiān shì xīngqī yī.","ko":"오늘은 월요일이다."},{"zh":"天空很蓝。","pinyin":"Tiānkōng hěn lán.","ko":"하늘이 파랗다."}],
"地":[{"zh":"地上有很多落叶。","pinyin":"Dìshang yǒu hěn duō luòyè.","ko":"땅 위에 낙엽이 많다."},{"zh":"这块地很肥沃。","pinyin":"Zhè kuài dì hěn féiwò.","ko":"이 땅은 비옥하다."}],
"金":[{"zh":"沉默是金。","pinyin":"Chénmò shì jīn.","ko":"침묵은 금이다."},{"zh":"她戴了一条金项链。","pinyin":"Tā dài le yī tiáo jīn xiàngliàn.","ko":"그녀는 금 목걸이를 했다."}],
"学":[{"zh":"我在学校学习。","pinyin":"Wǒ zài xuéxiào xuéxí.","ko":"나는 학교에서 공부한다."},{"zh":"学无止境。","pinyin":"Xué wú zhǐjìng.","ko":"배움에는 끝이 없다."}],
"生":[{"zh":"祝你生日快乐！","pinyin":"Zhù nǐ shēngrì kuàilè!","ko":"생일 축하합니다!"},{"zh":"学生们都很努力。","pinyin":"Xuéshēngmen dōu hěn nǔlì.","ko":"학생들은 모두 열심히 한다."}],
"心":[{"zh":"你的心意我收到了。","pinyin":"Nǐ de xīnyì wǒ shōudào le.","ko":"너의 마음을 받았다."},{"zh":"开心每一天。","pinyin":"Kāixīn měi yī tiān.","ko":"매일 즐겁게."}],
"手":[{"zh":"请洗手。","pinyin":"Qǐng xǐ shǒu.","ko":"손을 씻어 주세요."},{"zh":"她手里拿着一本书。","pinyin":"Tā shǒu lǐ ná zhe yī běn shū.","ko":"그녀는 손에 책을 들고 있다."}],
"目":[{"zh":"目前情况很好。","pinyin":"Mùqián qíngkuàng hěn hǎo.","ko":"현재 상황이 좋다."},{"zh":"他目光坚定。","pinyin":"Tā mùguāng jiāndìng.","ko":"그의 눈빛이 단호하다."}],
"口":[{"zh":"人口很多。","pinyin":"Rénkǒu hěn duō.","ko":"인구가 많다."},{"zh":"出口在那边。","pinyin":"Chūkǒu zài nàbiān.","ko":"출구가 저쪽에 있다."}],
"耳":[{"zh":"他的耳朵很灵。","pinyin":"Tā de ěrduo hěn líng.","ko":"그의 귀는 매우 밝다."},{"zh":"耳听为虚，眼见为实。","pinyin":"Ěr tīng wéi xū, yǎn jiàn wéi shí.","ko":"귀로 듣는 것은 허이고 눈으로 보는 것이 실이다."}],
"力":[{"zh":"他很有力气。","pinyin":"Tā hěn yǒu lìqi.","ko":"그는 힘이 세다."},{"zh":"我们要努力学习。","pinyin":"Wǒmen yào nǔlì xuéxí.","ko":"우리는 열심히 공부해야 한다."}],
"王":[{"zh":"王老师教我们数学。","pinyin":"Wáng lǎoshī jiāo wǒmen shùxué.","ko":"왕 선생님이 우리에게 수학을 가르친다."},{"zh":"他是国王。","pinyin":"Tā shì guówáng.","ko":"그는 왕이다."}],
"女":[{"zh":"那个女孩很漂亮。","pinyin":"Nàge nǚhái hěn piàoliang.","ko":"그 여자아이는 예쁘다."},{"zh":"女儿今年五岁。","pinyin":"Nǚ'ér jīnnián wǔ suì.","ko":"딸은 올해 다섯 살이다."}],
"子":[{"zh":"孩子们在玩。","pinyin":"Háizimen zài wán.","ko":"아이들이 놀고 있다."},{"zh":"桌子上有一个杯子。","pinyin":"Zhuōzi shàng yǒu yīgè bēizi.","ko":"탁자 위에 컵이 하나 있다."}],
"父":[{"zh":"父亲很爱我们。","pinyin":"Fùqin hěn ài wǒmen.","ko":"아버지는 우리를 사랑한다."},{"zh":"父母是最伟大的人。","pinyin":"Fùmǔ shì zuì wěidà de rén.","ko":"부모님은 가장 위대한 분이다."}],
"母":[{"zh":"母亲做的饭最好吃。","pinyin":"Mǔqin zuò de fàn zuì hǎochī.","ko":"어머니가 만든 밥이 제일 맛있다."},{"zh":"母爱是伟大的。","pinyin":"Mǔ'ài shì wěidà de.","ko":"모성애는 위대하다."}],
"花":[{"zh":"花园里开满了花。","pinyin":"Huāyuán lǐ kāi mǎn le huā.","ko":"정원에 꽃이 가득 피었다."},{"zh":"她喜欢买花。","pinyin":"Tā xǐhuan mǎi huā.","ko":"그녀는 꽃 사는 것을 좋아한다."}],
"草":[{"zh":"草地上有很多小虫。","pinyin":"Cǎodì shàng yǒu hěn duō xiǎo chóng.","ko":"잔디 위에 작은 벌레가 많다."},{"zh":"小草顽强地生长。","pinyin":"Xiǎocǎo wánqiáng de shēngzhǎng.","ko":"작은 풀이 강인하게 자란다."}],
"鸟":[{"zh":"树上有一只鸟。","pinyin":"Shù shàng yǒu yī zhī niǎo.","ko":"나무 위에 새 한 마리가 있다."},{"zh":"鸟儿在天空飞翔。","pinyin":"Niǎo'ér zài tiānkōng fēixiáng.","ko":"새가 하늘을 날고 있다."}],
"鱼":[{"zh":"我喜欢吃鱼。","pinyin":"Wǒ xǐhuan chī yú.","ko":"나는 생선 먹는 것을 좋아한다."},{"zh":"鱼在水里游。","pinyin":"Yú zài shuǐ lǐ yóu.","ko":"물고기가 물속에서 헤엄친다."}],
"马":[{"zh":"他骑马去了。","pinyin":"Tā qí mǎ qù le.","ko":"그는 말을 타고 갔다."},{"zh":"马上就来。","pinyin":"Mǎshàng jiù lái.","ko":"곧 올게요."}],
"牛":[{"zh":"牛在田里吃草。","pinyin":"Niú zài tián lǐ chī cǎo.","ko":"소가 밭에서 풀을 먹고 있다."},{"zh":"他很牛。","pinyin":"Tā hěn niú.","ko":"그는 대단하다."}],
"羊":[{"zh":"山上有一群羊。","pinyin":"Shān shàng yǒu yī qún yáng.","ko":"산 위에 양 떼가 있다."},{"zh":"羊肉很好吃。","pinyin":"Yángròu hěn hǎochī.","ko":"양고기가 맛있다."}],
"犬":[{"zh":"犬吠声很大。","pinyin":"Quǎn fèi shēng hěn dà.","ko":"개 짖는 소리가 크다."},{"zh":"他养了一只小犬。","pinyin":"Tā yǎng le yī zhī xiǎo quǎn.","ko":"그는 작은 개 한 마리를 기른다."}],
"食":[{"zh":"食物很丰富。","pinyin":"Shíwù hěn fēngfù.","ko":"음식이 풍부하다."},{"zh":"民以食为天。","pinyin":"Mín yǐ shí wéi tiān.","ko":"백성은 먹는 것을 하늘로 여긴다."}],
"衣":[{"zh":"她穿了一件新衣服。","pinyin":"Tā chuān le yī jiàn xīn yīfu.","ko":"그녀는 새 옷을 입었다."},{"zh":"衣食住行。","pinyin":"Yī shí zhù xíng.","ko":"의식주와 교통."}],
"上":[{"zh":"请上车。","pinyin":"Qǐng shàng chē.","ko":"차에 타세요."},{"zh":"桌子上有一本书。","pinyin":"Zhuōzi shàng yǒu yī běn shū.","ko":"탁자 위에 책이 있다."}],
"下":[{"zh":"请下车。","pinyin":"Qǐng xià chē.","ko":"차에서 내리세요."},{"zh":"下午我有课。","pinyin":"Xiàwǔ wǒ yǒu kè.","ko":"오후에 수업이 있다."}],
"左":[{"zh":"左边是银行。","pinyin":"Zuǒbiān shì yínháng.","ko":"왼쪽이 은행이다."},{"zh":"请向左转。","pinyin":"Qǐng xiàng zuǒ zhuǎn.","ko":"왼쪽으로 돌아주세요."}],
"右":[{"zh":"右边是邮局。","pinyin":"Yòubiān shì yóujú.","ko":"오른쪽이 우체국이다."},{"zh":"请向右走。","pinyin":"Qǐng xiàng yòu zǒu.","ko":"오른쪽으로 가세요."}],
"前":[{"zh":"前面有一个路口。","pinyin":"Qiánmiàn yǒu yīgè lùkǒu.","ko":"앞에 교차로가 있다."},{"zh":"以前我住在北京。","pinyin":"Yǐqián wǒ zhù zài Běijīng.","ko":"예전에 나는 베이징에 살았다."}],
"后":[{"zh":"后面有人在叫你。","pinyin":"Hòumiàn yǒu rén zài jiào nǐ.","ko":"뒤에서 누군가 너를 부르고 있다."},{"zh":"以后再说吧。","pinyin":"Yǐhòu zài shuō ba.","ko":"나중에 이야기하자."}],
"东":[{"zh":"太阳从东方升起。","pinyin":"Tàiyáng cóng dōngfāng shēngqǐ.","ko":"태양은 동쪽에서 뜬다."},{"zh":"东京是日本的首都。","pinyin":"Dōngjīng shì Rìběn de shǒudū.","ko":"도쿄는 일본의 수도이다."}],
"西":[{"zh":"西瓜很甜。","pinyin":"Xīguā hěn tián.","ko":"수박이 달다."},{"zh":"他去了西安。","pinyin":"Tā qù le Xī'ān.","ko":"그는 시안에 갔다."}],
"南":[{"zh":"南方的冬天不太冷。","pinyin":"Nánfāng de dōngtiān bú tài lěng.","ko":"남쪽의 겨울은 그리 춥지 않다."},{"zh":"南京是古都。","pinyin":"Nánjīng shì gǔdū.","ko":"난징은 고도이다."}],
"北":[{"zh":"北京是中国的首都。","pinyin":"Běijīng shì Zhōngguó de shǒudū.","ko":"베이징은 중국의 수도이다."},{"zh":"北方很冷。","pinyin":"Běifāng hěn lěng.","ko":"북쪽은 춥다."}],
"白":[{"zh":"白雪覆盖了大地。","pinyin":"Bái xuě fùgài le dàdì.","ko":"흰 눈이 대지를 덮었다."},{"zh":"他穿了一件白衬衫。","pinyin":"Tā chuān le yī jiàn bái chènshān.","ko":"그는 흰 셔츠를 입었다."}],
"黑":[{"zh":"天黑了。","pinyin":"Tiān hēi le.","ko":"날이 어두워졌다."},{"zh":"她有一双黑眼睛。","pinyin":"Tā yǒu yī shuāng hēi yǎnjing.","ko":"그녀는 까만 눈을 가지고 있다."}],
"红":[{"zh":"她穿了一件红裙子。","pinyin":"Tā chuān le yī jiàn hóng qúnzi.","ko":"그녀는 빨간 치마를 입었다."},{"zh":"红灯停，绿灯行。","pinyin":"Hóng dēng tíng, lǜ dēng xíng.","ko":"빨간불에 멈추고 초록불에 간다."}],
"蓝":[{"zh":"天空是蓝色的。","pinyin":"Tiānkōng shì lán sè de.","ko":"하늘은 파란색이다."},{"zh":"她穿了一条蓝裤子。","pinyin":"Tā chuān le yī tiáo lán kùzi.","ko":"그녀는 파란 바지를 입었다."}],
"绿":[{"zh":"绿树成荫。","pinyin":"Lǜ shù chéngyīn.","ko":"푸른 나무가 그늘을 이룬다."},{"zh":"草地是绿色的。","pinyin":"Cǎodì shì lǜsè de.","ko":"잔디는 초록색이다."}],
"黄":[{"zh":"秋天树叶变黄了。","pinyin":"Qiūtiān shùyè biàn huáng le.","ko":"가을에 나뭇잎이 노랗게 변한다."},{"zh":"黄河是中国的母亲河。","pinyin":"Huánghé shì Zhōngguó de mǔqīn hé.","ko":"황하는 중국의 어머니 강이다."}],
"好":[{"zh":"今天天气真好。","pinyin":"Jīntiān tiānqì zhēn hǎo.","ko":"오늘 날씨가 정말 좋다."},{"zh":"你好！很高兴认识你。","pinyin":"Nǐ hǎo! Hěn gāoxìng rènshi nǐ.","ko":"안녕하세요! 만나서 반갑습니다."}],
"爱":[{"zh":"我爱我的家人。","pinyin":"Wǒ ài wǒ de jiārén.","ko":"나는 가족을 사랑한다."},{"zh":"爱是最伟大的力量。","pinyin":"Ài shì zuì wěidà de lìliang.","ko":"사랑은 가장 위대한 힘이다."}],
"友":[{"zh":"他是我最好的朋友。","pinyin":"Tā shì wǒ zuì hǎo de péngyou.","ko":"그는 나의 가장 친한 친구이다."},{"zh":"友谊地久天长。","pinyin":"Yǒuyì dìjiǔ tiāncháng.","ko":"우정은 영원하다."}],
"家":[{"zh":"我家在北京。","pinyin":"Wǒ jiā zài Běijīng.","ko":"우리 집은 베이징에 있다."},{"zh":"回家吃饭。","pinyin":"Huí jiā chīfàn.","ko":"집에 가서 밥 먹자."}],
"国":[{"zh":"中国历史悠久。","pinyin":"Zhōngguó lìshǐ yōujiǔ.","ko":"중국 역사는 유구하다."},{"zh":"我爱我的国家。","pinyin":"Wǒ ài wǒ de guójiā.","ko":"나는 내 나라를 사랑한다."}],
"年":[{"zh":"新年快乐！","pinyin":"Xīnnián kuàilè!","ko":"새해 복 많이 받으세요!"},{"zh":"他今年二十岁。","pinyin":"Tā jīnnián èrshí suì.","ko":"그는 올해 스무 살이다."}],
"来":[{"zh":"请过来。","pinyin":"Qǐng guòlái.","ko":"이쪽으로 오세요."},{"zh":"他来自韩国。","pinyin":"Tā láizì Hánguó.","ko":"그는 한국에서 왔다."}],
"去":[{"zh":"我想去中国旅游。","pinyin":"Wǒ xiǎng qù Zhōngguó lǚyóu.","ko":"나는 중국으로 여행 가고 싶다."},{"zh":"去哪里？","pinyin":"Qù nǎlǐ?","ko":"어디에 가나요?"}],
"吃":[{"zh":"我们去吃午饭。","pinyin":"Wǒmen qù chī wǔfàn.","ko":"점심 먹으러 가자."},{"zh":"你吃过了吗？","pinyin":"Nǐ chī guò le ma?","ko":"밥 먹었어요?"}],
"喝":[{"zh":"请喝茶。","pinyin":"Qǐng hē chá.","ko":"차를 드세요."},{"zh":"我想喝咖啡。","pinyin":"Wǒ xiǎng hē kāfēi.","ko":"커피 마시고 싶다."}],
"看":[{"zh":"我在看电视。","pinyin":"Wǒ zài kàn diànshì.","ko":"나는 TV를 보고 있다."},{"zh":"看一看这本书。","pinyin":"Kàn yi kàn zhè běn shū.","ko":"이 책을 한번 봐."}],
"听":[{"zh":"我在听音乐。","pinyin":"Wǒ zài tīng yīnyuè.","ko":"나는 음악을 듣고 있다."},{"zh":"听说明天下雨。","pinyin":"Tīngshuō míngtiān xià yǔ.","ko":"내일 비가 온다고 들었다."}],
"说":[{"zh":"请你说慢一点。","pinyin":"Qǐng nǐ shuō màn yīdiǎn.","ko":"천천히 말해 주세요."},{"zh":"他说得很好。","pinyin":"Tā shuō de hěn hǎo.","ko":"그는 말을 잘한다."}],
"读":[{"zh":"我每天读书。","pinyin":"Wǒ měitiān dúshū.","ko":"나는 매일 책을 읽는다."},{"zh":"请大声读。","pinyin":"Qǐng dàshēng dú.","ko":"크게 소리내어 읽어주세요."}],
"写":[{"zh":"请写你的名字。","pinyin":"Qǐng xiě nǐ de míngzi.","ko":"이름을 써주세요."},{"zh":"他在写作业。","pinyin":"Tā zài xiě zuòyè.","ko":"그는 숙제를 하고 있다."}],
"走":[{"zh":"我们走路去吧。","pinyin":"Wǒmen zǒulù qù ba.","ko":"걸어서 가자."},{"zh":"他走了。","pinyin":"Tā zǒu le.","ko":"그는 떠났다."}],
"跑":[{"zh":"他每天跑步。","pinyin":"Tā měitiān pǎobù.","ko":"그는 매일 달리기를 한다."},{"zh":"别跑，小心摔倒。","pinyin":"Bié pǎo, xiǎoxīn shuāidǎo.","ko":"뛰지 마, 넘어질라."}],
"飞":[{"zh":"飞机飞得很高。","pinyin":"Fēijī fēi de hěn gāo.","ko":"비행기가 높이 날고 있다."},{"zh":"鸟儿在飞。","pinyin":"Niǎo'ér zài fēi.","ko":"새가 날고 있다."}],
"车":[{"zh":"他开车去上班。","pinyin":"Tā kāichē qù shàngbān.","ko":"그는 운전해서 출근한다."},{"zh":"公共汽车很方便。","pinyin":"Gōnggòng qìchē hěn fāngbiàn.","ko":"버스가 편리하다."}],
"书":[{"zh":"我喜欢看书。","pinyin":"Wǒ xǐhuan kàn shū.","ko":"나는 독서를 좋아한다."},{"zh":"这本书很有趣。","pinyin":"Zhè běn shū hěn yǒuqù.","ko":"이 책은 재미있다."}],
"门":[{"zh":"请关门。","pinyin":"Qǐng guān mén.","ko":"문을 닫아 주세요."},{"zh":"门口有人等你。","pinyin":"Ménkǒu yǒu rén děng nǐ.","ko":"문 앞에 누가 널 기다리고 있다."}],
"雨":[{"zh":"外面下雨了。","pinyin":"Wàimiàn xià yǔ le.","ko":"밖에 비가 온다."},{"zh":"别忘了带雨伞。","pinyin":"Bié wàng le dài yǔsǎn.","ko":"우산 가져가는 것 잊지 마."}],
"雪":[{"zh":"下雪了，好美。","pinyin":"Xià xuě le, hǎo měi.","ko":"눈이 온다, 아름답다."},{"zh":"雪人很可爱。","pinyin":"Xuěrén hěn kě'ài.","ko":"눈사람이 귀엽다."}],
"风":[{"zh":"今天风很大。","pinyin":"Jīntiān fēng hěn dà.","ko":"오늘 바람이 세다."},{"zh":"春风吹来了。","pinyin":"Chūnfēng chuī lái le.","ko":"봄바람이 불어왔다."}],
"电":[{"zh":"请充电。","pinyin":"Qǐng chōngdiàn.","ko":"충전하세요."},{"zh":"电话响了。","pinyin":"Diànhuà xiǎng le.","ko":"전화가 울렸다."}],
"话":[{"zh":"我有话要说。","pinyin":"Wǒ yǒu huà yào shuō.","ko":"할 말이 있다."},{"zh":"他打了一个电话。","pinyin":"Tā dǎ le yīgè diànhuà.","ko":"그는 전화를 한 통 했다."}],
"长":[{"zh":"万里长城很壮观。","pinyin":"Wànlǐ Chángchéng hěn zhuàngguān.","ko":"만리장성은 장관이다."},{"zh":"他长得很高。","pinyin":"Tā zhǎng de hěn gāo.","ko":"그는 키가 크다."}],
"高":[{"zh":"这栋楼很高。","pinyin":"Zhè dòng lóu hěn gāo.","ko":"이 건물은 높다."},{"zh":"他的水平很高。","pinyin":"Tā de shuǐpíng hěn gāo.","ko":"그의 수준이 높다."}],
"多":[{"zh":"商店里人很多。","pinyin":"Shāngdiàn lǐ rén hěn duō.","ko":"가게에 사람이 많다."},{"zh":"多谢你的帮助。","pinyin":"Duōxiè nǐ de bāngzhù.","ko":"도와줘서 고마워."}],
"少":[{"zh":"这里人很少。","pinyin":"Zhèlǐ rén hěn shǎo.","ko":"여기는 사람이 적다."},{"zh":"少说多做。","pinyin":"Shǎo shuō duō zuò.","ko":"말은 적게 하고 행동은 많이 해라."}],
"老":[{"zh":"老师好！","pinyin":"Lǎoshī hǎo!","ko":"선생님 안녕하세요!"},{"zh":"这个老人很慈祥。","pinyin":"Zhège lǎorén hěn cíxiáng.","ko":"이 노인은 자상하다."}],
"新":[{"zh":"新年新气象。","pinyin":"Xīnnián xīn qìxiàng.","ko":"새해 새 기운."},{"zh":"我买了一件新衣服。","pinyin":"Wǒ mǎi le yī jiàn xīn yīfu.","ko":"새 옷을 샀다."}],
"明":[{"zh":"明天见。","pinyin":"Míngtiān jiàn.","ko":"내일 봐."},{"zh":"这个道理很明白。","pinyin":"Zhège dàolǐ hěn míngbai.","ko":"이 도리는 분명하다."}],
"早":[{"zh":"早上好！","pinyin":"Zǎoshang hǎo!","ko":"좋은 아침!"},{"zh":"他每天很早起床。","pinyin":"Tā měitiān hěn zǎo qǐchuáng.","ko":"그는 매일 일찍 일어난다."}],
"晚":[{"zh":"晚安。","pinyin":"Wǎn'ān.","ko":"안녕히 주무세요."},{"zh":"太晚了，回家吧。","pinyin":"Tài wǎn le, huí jiā ba.","ko":"너무 늦었어, 집에 가자."}],
"春":[{"zh":"春天来了。","pinyin":"Chūntiān lái le.","ko":"봄이 왔다."},{"zh":"一年之计在于春。","pinyin":"Yī nián zhī jì zài yú chūn.","ko":"일 년의 계획은 봄에 있다."}],
"夏":[{"zh":"夏天很热。","pinyin":"Xiàtiān hěn rè.","ko":"여름은 덥다."},{"zh":"暑假我去了海边。","pinyin":"Shǔjià wǒ qù le hǎibiān.","ko":"여름방학에 바닷가에 갔다."}],
"秋":[{"zh":"秋天是收获的季节。","pinyin":"Qiūtiān shì shōuhuò de jìjié.","ko":"가을은 수확의 계절이다."},{"zh":"秋风送爽。","pinyin":"Qiūfēng sòng shuǎng.","ko":"가을 바람이 시원하다."}],
"冬":[{"zh":"冬天下雪。","pinyin":"Dōngtiān xià xuě.","ko":"겨울에 눈이 온다."},{"zh":"冬天要多穿衣服。","pinyin":"Dōngtiān yào duō chuān yīfu.","ko":"겨울에는 옷을 많이 입어야 한다."}],
"头":[{"zh":"他头疼。","pinyin":"Tā tóu téng.","ko":"그는 머리가 아프다."},{"zh":"回头看一看。","pinyin":"Huítóu kàn yi kàn.","ko":"뒤돌아 한번 봐."}],
"发":[{"zh":"她的头发很长。","pinyin":"Tā de tóufa hěn cháng.","ko":"그녀의 머리카락이 길다."},{"zh":"我发现了一个问题。","pinyin":"Wǒ fāxiàn le yīgè wèntí.","ko":"문제를 하나 발견했다."}],
"身":[{"zh":"身体健康最重要。","pinyin":"Shēntǐ jiànkāng zuì zhòngyào.","ko":"건강이 가장 중요하다."},{"zh":"他身材很好。","pinyin":"Tā shēncái hěn hǎo.","ko":"그는 체격이 좋다."}],
"足":[{"zh":"知足常乐。","pinyin":"Zhīzú chánglè.","ko":"만족을 알면 항상 즐겁다."},{"zh":"足球比赛很精彩。","pinyin":"Zúqiú bǐsài hěn jīngcǎi.","ko":"축구 경기가 정말 멋졌다."}],
"气":[{"zh":"今天天气很好。","pinyin":"Jīntiān tiānqì hěn hǎo.","ko":"오늘 날씨가 좋다."},{"zh":"别生气了。","pinyin":"Bié shēngqì le.","ko":"화내지 마."}],
"开":[{"zh":"请开门。","pinyin":"Qǐng kāi mén.","ko":"문을 열어 주세요."},{"zh":"商店几点开门？","pinyin":"Shāngdiàn jǐ diǎn kāimén?","ko":"가게는 몇 시에 여나요?"}],
"关":[{"zh":"请关灯。","pinyin":"Qǐng guān dēng.","ko":"불 좀 꺼주세요."},{"zh":"这件事跟我没关系。","pinyin":"Zhè jiàn shì gēn wǒ méi guānxi.","ko":"이 일은 나와 관계없다."}],
"工":[{"zh":"他在工厂工作。","pinyin":"Tā zài gōngchǎng gōngzuò.","ko":"그는 공장에서 일한다."},{"zh":"这个工程很大。","pinyin":"Zhège gōngchéng hěn dà.","ko":"이 공사는 크다."}],
"用":[{"zh":"这个很有用。","pinyin":"Zhège hěn yǒuyòng.","ko":"이것은 유용하다."},{"zh":"不用谢。","pinyin":"Búyòng xiè.","ko":"천만에요."}],
"知":[{"zh":"你知道吗？","pinyin":"Nǐ zhīdào ma?","ko":"알아요?"},{"zh":"知识就是力量。","pinyin":"Zhīshi jiùshì lìliang.","ko":"지식이 곧 힘이다."}],
"道":[{"zh":"你知道路吗？","pinyin":"Nǐ zhīdào lù ma?","ko":"길을 아세요?"},{"zh":"道理很简单。","pinyin":"Dàolǐ hěn jiǎndān.","ko":"이치는 간단하다."}],
"思":[{"zh":"我很想你。","pinyin":"Wǒ hěn xiǎng nǐ.","ko":"너를 많이 그리워한다."},{"zh":"三思而后行。","pinyin":"Sān sī ér hòu xíng.","ko":"세 번 생각한 후에 행동하라."}],
"想":[{"zh":"我想回家。","pinyin":"Wǒ xiǎng huí jiā.","ko":"집에 가고 싶다."},{"zh":"你想吃什么？","pinyin":"Nǐ xiǎng chī shénme?","ko":"뭘 먹고 싶어?"}],
"会":[{"zh":"你会说中文吗？","pinyin":"Nǐ huì shuō zhōngwén ma?","ko":"중국어 할 줄 아세요?"},{"zh":"明天有一个会议。","pinyin":"Míngtiān yǒu yīgè huìyì.","ko":"내일 회의가 있다."}],
"能":[{"zh":"你能帮我吗？","pinyin":"Nǐ néng bāng wǒ ma?","ko":"나를 도와줄 수 있어?"},{"zh":"他能跑得很快。","pinyin":"Tā néng pǎo de hěn kuài.","ko":"그는 빨리 달릴 수 있다."}],
"可":[{"zh":"可以进来吗？","pinyin":"Kěyǐ jìnlái ma?","ko":"들어가도 될까요?"},{"zh":"可能明天下雨。","pinyin":"Kěnéng míngtiān xià yǔ.","ko":"내일 비가 올 수도 있다."}],
"要":[{"zh":"我要一杯咖啡。","pinyin":"Wǒ yào yī bēi kāfēi.","ko":"커피 한 잔 주세요."},{"zh":"重要的是健康。","pinyin":"Zhòngyào de shì jiànkāng.","ko":"중요한 것은 건강이다."}],
"很":[{"zh":"她很漂亮。","pinyin":"Tā hěn piàoliang.","ko":"그녀는 예쁘다."},{"zh":"这道菜很好吃。","pinyin":"Zhè dào cài hěn hǎochī.","ko":"이 요리는 맛있다."}],
"不":[{"zh":"我不知道。","pinyin":"Wǒ bù zhīdào.","ko":"모르겠다."},{"zh":"他不在家。","pinyin":"Tā bú zài jiā.","ko":"그는 집에 없다."}],
"也":[{"zh":"我也想去。","pinyin":"Wǒ yě xiǎng qù.","ko":"나도 가고 싶다."},{"zh":"他也是学生。","pinyin":"Tā yě shì xuéshēng.","ko":"그도 학생이다."}],
"都":[{"zh":"大家都来了。","pinyin":"Dàjiā dōu lái le.","ko":"모두 왔다."},{"zh":"什么都好。","pinyin":"Shénme dōu hǎo.","ko":"뭐든 좋다."}],
"有":[{"zh":"我有一个问题。","pinyin":"Wǒ yǒu yīgè wèntí.","ko":"질문이 하나 있다."},{"zh":"这里有很多树。","pinyin":"Zhèlǐ yǒu hěn duō shù.","ko":"여기 나무가 많다."}],
"没":[{"zh":"我没有钱。","pinyin":"Wǒ méiyǒu qián.","ko":"돈이 없다."},{"zh":"他没来。","pinyin":"Tā méi lái.","ko":"그는 오지 않았다."}],
"是":[{"zh":"我是韩国人。","pinyin":"Wǒ shì Hánguó rén.","ko":"나는 한국 사람이다."},{"zh":"这是什么？","pinyin":"Zhè shì shénme?","ko":"이것은 무엇인가?"}],
"在":[{"zh":"我在家。","pinyin":"Wǒ zài jiā.","ko":"나는 집에 있다."},{"zh":"他在看书。","pinyin":"Tā zài kàn shū.","ko":"그는 책을 읽고 있다."}],
"的":[{"zh":"这是我的书。","pinyin":"Zhè shì wǒ de shū.","ko":"이것은 내 책이다."},{"zh":"红色的花很漂亮。","pinyin":"Hóngsè de huā hěn piàoliang.","ko":"빨간 꽃이 예쁘다."}],
"了":[{"zh":"我吃了饭。","pinyin":"Wǒ chī le fàn.","ko":"밥을 먹었다."},{"zh":"他走了。","pinyin":"Tā zǒu le.","ko":"그는 갔다."}],
"和":[{"zh":"我和他是朋友。","pinyin":"Wǒ hé tā shì péngyou.","ko":"나와 그는 친구이다."},{"zh":"和平很重要。","pinyin":"Hépíng hěn zhòngyào.","ko":"평화는 중요하다."}],
"美":[{"zh":"风景很美。","pinyin":"Fēngjǐng hěn měi.","ko":"풍경이 아름답다."},{"zh":"美食令人愉快。","pinyin":"Měishí lìng rén yúkuài.","ko":"맛있는 음식은 즐겁게 한다."}],
"快":[{"zh":"快点走吧。","pinyin":"Kuài diǎn zǒu ba.","ko":"빨리 가자."},{"zh":"他跑得很快。","pinyin":"Tā pǎo de hěn kuài.","ko":"그는 매우 빨리 달린다."}],
"乐":[{"zh":"快乐每一天。","pinyin":"Kuàilè měi yī tiān.","ko":"매일 즐겁게."},{"zh":"音乐让人放松。","pinyin":"Yīnyuè ràng rén fàngsōng.","ko":"음악은 사람을 편안하게 한다."}],
"谢":[{"zh":"谢谢你！","pinyin":"Xièxie nǐ!","ko":"감사합니다!"},{"zh":"不用谢。","pinyin":"Búyòng xiè.","ko":"천만에요."}],
"对":[{"zh":"你说得对。","pinyin":"Nǐ shuō de duì.","ko":"네 말이 맞다."},{"zh":"对不起。","pinyin":"Duìbuqǐ.","ko":"미안합니다."}],
"错":[{"zh":"我做错了。","pinyin":"Wǒ zuò cuò le.","ko":"내가 잘못했다."},{"zh":"这道题答错了。","pinyin":"Zhè dào tí dá cuò le.","ko":"이 문제를 틀렸다."}],
"钱":[{"zh":"这个多少钱？","pinyin":"Zhège duōshao qián?","ko":"이것은 얼마인가요?"},{"zh":"钱不是万能的。","pinyin":"Qián búshì wànnéng de.","ko":"돈이 전부는 아니다."}],
"买":[{"zh":"我想买一件衣服。","pinyin":"Wǒ xiǎng mǎi yī jiàn yīfu.","ko":"옷 한 벌 사고 싶다."},{"zh":"去超市买东西。","pinyin":"Qù chāoshì mǎi dōngxi.","ko":"슈퍼마켓에 물건 사러 간다."}],
"卖":[{"zh":"他卖水果。","pinyin":"Tā mài shuǐguǒ.","ko":"그는 과일을 판다."},{"zh":"这个东西不卖。","pinyin":"Zhège dōngxi bú mài.","ko":"이것은 팔지 않는다."}],
"吗":[{"zh":"你好吗？","pinyin":"Nǐ hǎo ma?","ko":"잘 지내요?"},{"zh":"你是学生吗？","pinyin":"Nǐ shì xuéshēng ma?","ko":"학생이에요?"}],
"什":[{"zh":"你叫什么名字？","pinyin":"Nǐ jiào shénme míngzi?","ko":"이름이 뭐에요?"},{"zh":"什么时候出发？","pinyin":"Shénme shíhou chūfā?","ko":"언제 출발해요?"}],
"么":[{"zh":"怎么了？","pinyin":"Zěnme le?","ko":"왜 그래?"},{"zh":"那么我先走了。","pinyin":"Nàme wǒ xiān zǒu le.","ko":"그러면 먼저 갈게."}],
"哪":[{"zh":"你是哪国人？","pinyin":"Nǐ shì nǎ guó rén?","ko":"어느 나라 사람이에요?"},{"zh":"哪里有餐厅？","pinyin":"Nǎlǐ yǒu cāntīng?","ko":"어디에 식당이 있어요?"}],
"几":[{"zh":"现在几点了？","pinyin":"Xiànzài jǐ diǎn le?","ko":"지금 몇 시에요?"},{"zh":"你有几个孩子？","pinyin":"Nǐ yǒu jǐ gè háizi?","ko":"아이가 몇 명이에요?"}],
"块":[{"zh":"这块蛋糕很好吃。","pinyin":"Zhè kuài dàngāo hěn hǎochī.","ko":"이 케이크 조각은 맛있다."},{"zh":"一块钱。","pinyin":"Yī kuài qián.","ko":"1위안."}],
"两":[{"zh":"我有两个哥哥。","pinyin":"Wǒ yǒu liǎng gè gēge.","ko":"형이 두 명 있다."},{"zh":"两个小时。","pinyin":"Liǎng gè xiǎoshí.","ko":"두 시간."}],
"半":[{"zh":"现在三点半。","pinyin":"Xiànzài sān diǎn bàn.","ko":"지금 3시 반이다."},{"zh":"半个西瓜。","pinyin":"Bàn gè xīguā.","ko":"수박 반 통."}],
"面":[{"zh":"我喜欢吃面条。","pinyin":"Wǒ xǐhuan chī miàntiáo.","ko":"나는 국수를 좋아한다."},{"zh":"面前有一条路。","pinyin":"Miànqián yǒu yī tiáo lù.","ko":"앞에 길이 있다."}],
"里":[{"zh":"家里有人吗？","pinyin":"Jiā lǐ yǒu rén ma?","ko":"집에 사람 있어요?"},{"zh":"心里很高兴。","pinyin":"Xīn lǐ hěn gāoxìng.","ko":"마음이 기쁘다."}],
"外":[{"zh":"外面在下雨。","pinyin":"Wàimiàn zài xià yǔ.","ko":"밖에 비가 오고 있다."},{"zh":"他在国外工作。","pinyin":"Tā zài guówài gōngzuò.","ko":"그는 해외에서 일한다."}],
"回":[{"zh":"我要回家了。","pinyin":"Wǒ yào huí jiā le.","ko":"집에 가야겠다."},{"zh":"回来得很晚。","pinyin":"Huílái de hěn wǎn.","ko":"매우 늦게 돌아왔다."}],
"还":[{"zh":"他还没来。","pinyin":"Tā hái méi lái.","ko":"그는 아직 안 왔다."},{"zh":"我还想再去一次。","pinyin":"Wǒ hái xiǎng zài qù yī cì.","ko":"한 번 더 가고 싶다."}],
"过":[{"zh":"你吃过中国菜吗？","pinyin":"Nǐ chī guò Zhōngguó cài ma?","ko":"중국 요리 먹어본 적 있어요?"},{"zh":"过马路要小心。","pinyin":"Guò mǎlù yào xiǎoxīn.","ko":"길을 건널 때 조심해야 한다."}],
"给":[{"zh":"请给我一杯水。","pinyin":"Qǐng gěi wǒ yī bēi shuǐ.","ko":"물 한 잔 주세요."},{"zh":"她给了我一枚硬币。","pinyin":"Tā gěi le wǒ yī méi yìngbì.","ko":"그녀는 나에게 동전 한 개를 주었다."}],
"让":[{"zh":"请让一让。","pinyin":"Qǐng ràng yi ràng.","ko":"좀 비켜 주세요."},{"zh":"这件事让我很感动。","pinyin":"Zhè jiàn shì ràng wǒ hěn gǎndòng.","ko":"이 일은 나를 감동시켰다."}],
"把":[{"zh":"把门关上。","pinyin":"Bǎ mén guān shàng.","ko":"문을 닫아라."},{"zh":"他把书放在桌子上。","pinyin":"Tā bǎ shū fàng zài zhuōzi shàng.","ko":"그는 책을 탁자 위에 놓았다."}],
"被":[{"zh":"他被雨淋湿了。","pinyin":"Tā bèi yǔ lín shī le.","ko":"그는 비에 젖었다."},{"zh":"蛋糕被吃完了。","pinyin":"Dàngāo bèi chī wán le.","ko":"케이크가 다 먹혔다."}],
"做":[{"zh":"你在做什么？","pinyin":"Nǐ zài zuò shénme?","ko":"뭐 하고 있어?"},{"zh":"我在做作业。","pinyin":"Wǒ zài zuò zuòyè.","ko":"숙제하고 있다."}],
"到":[{"zh":"我到了。","pinyin":"Wǒ dào le.","ko":"도착했다."},{"zh":"从早到晚。","pinyin":"Cóng zǎo dào wǎn.","ko":"아침부터 저녁까지."}],
"再":[{"zh":"再见！","pinyin":"Zàijiàn!","ko":"안녕히 가세요!"},{"zh":"请再说一遍。","pinyin":"Qǐng zài shuō yī biàn.","ko":"다시 한번 말해 주세요."}],
"先":[{"zh":"你先走吧。","pinyin":"Nǐ xiān zǒu ba.","ko":"먼저 가."},{"zh":"先吃饭再说。","pinyin":"Xiān chīfàn zài shuō.","ko":"먼저 밥 먹고 이야기하자."}]
};
